### PR TITLE
Add string constants for conferences and journals

### PR DESCRIPTION
**Pull request by omersahintas**
This PR removes a duplicate key and adds entries for conferences and journals.

There is an issue that needs to be taken care of while merging:
The duplicate key removal might cause problems if the SISL website uses this key.

### CODE REVIEW

**Comment by mykelk** [comment]
Can you make sure the strings are sorted? It will make it easier to find things in the list. Thanks!

**Comment by mykelk** [comment]
I think we lost wafr in the process?

**Comment by omersahintas** [comment]
You are right. We lost wafr in the process.

I've sorted all the entries and added wafr. I think, it should be fine this PR now.

**Comment by mykelk** [comment]
Thanks!

**Pull request merged**
